#!/bin/python3

f = open("input")
inp = f.read()
f.close()
entries = inp.split(",")
ids = []
for entry in entries:
    a = int(entry.split("-")[0])
    b = int(entry.split("-")[1])
    ids += list(range(a, b+1))

invalids = []
for nb in ids:
    if (len(str(nb)) % 2) == 0:
        strv = str(nb)
        halflen = int(len(strv) / 2)
        half = strv[:halflen]
        if strv[halflen:] == half:
            invalids += [nb]

total = 0
for nb in invalids:
    total += nb

print(total)
